### ISSUE TITLE
Where do we put routing function logic?

### ISSUE THREAD

**Issue by kissartisan** [x-team/golang-peer-learning#1]
## Where do we put routing function logic?
- Should we put them in some kind of a controller directory? 
   - If so, how do we do that?

<img width="742" alt="Screenshot 2024-04-04 at 17 51 23" src="https://github.com/x-team/golang-peer-learning/assets/12791515/ae2c18cf-3402-4cd3-9461-9936fe374734">

**Comment by andrerfarias** [comment]
Yeah makes sense having a file for each rout domain, for example `messagesRoutes.go` and then have the message routes mapped in there.

Wdyt?

I can raise a PR with the change if you agree.

**Comment by kissartisan** [comment]
Honestly, I'm having a hard time to tinker through Go. 😅  

So using PRs for as samples are great way to learn! Thanks mate @andrerfarias !

**Comment by andrerfarias** [comment]
@kissartisan 
https://github.com/x-team/golang-peer-learning/pull/3
